#!/bin/bash
# screen (wayland) + audio from screen + micro capturing

# pavucontrol & \
# killall -9 pavucontrol

dir=$HOME/Videos
name=$(date | awk '{print $2 "-" $3 "-" $7}')

MONITOR_SRC="$(pactl list short sources | grep 'monitor' | bemenu -i -l 10 'select monitor source')"
INPUT_SRC="$(pactl list short sources | grep 'input' | bemenu -i -l 10 'select input source')"

ffmpeg \
    -f pipewire -i pipewire: \
    -f pulse -i "$MONITOR_SRC" \
    -f pulse -i "$INPUT_SRC" \
    -f x11grab \
    -filter_complex "[1:a][2:a]amix=inputs=2:duration=longest[aout]" \
    -map 0:v -map "[aout]" \
    -c:v libx264 -preset ultrafast -crf 25 \
    -c:a aac -b:a 128k \
    $dir/$name-$(($(ls $dir | grep $name | wc -l)+1)).mkv
