#!/bin/bash

#
# Convinient way of searching in Chromes' bookmarks
#

BOOKMARKS_PATH="$HOME/.config/chromium/Default/Bookmarks"

BKM=$(jq -r "
  .roots.bookmark_bar.children[]
  | select(.name? == \"kroll's\")
  | .children[]
  | select(.name? == \"Speed Dials\")
  | .children[]
  | \"\(.url) -- \u001b[35m\(.name)\u001b[0m\"" "$BOOKMARKS_PATH" | fzf --ansi)

[ -z "$BKM" ] && echo "No selection made." && exit 1

URL=$(echo "$BKM" | awk -F' -- ' '{print $1}')
NAME=$(echo "$BKM" | awk -F' -- ' '{print $2}')

if command -v xclip &>/dev/null; then
    echo -n "$URL" | xclip -selection clipboard
else
    echo "xclip not found"
    exit 1
fi

echo "Copied🐧"
