#!/bin/bash

X=$(date -d "2025-04-10 22:45" +%s); 
while true; do 
    printf "⚔️ДО КОНЦА БОТКИ ОСТАЛОСЬ\n*%d ЧАСОВ %d минут*\n" \
    "$(( ($X - `date +%s`) / 3600 ))" \
    "$(( ($X - `date +%s`) % 3600 / 60 ))" | tg-send; 
    sleep 7200; 
done
