#!/bin/bash
# screen + micro capturing

pavucontrol & \
killall -9 pavucontrol

dir=$HOME/Videos
name=$(date | awk '{print $2 "-" $3 "-" $7}')

ffmpeg -f alsa -ac 2 -i default \
-channel_layout stereo \
-f x11grab \
-framerate 30 \
-s $(xrandr --current | grep -i '*' | awk '{print $1;}') \
-i :0.0+0,0 \
-c:v libx264 \
-preset ultrafast -crf 25 \
-c:a aac \
-threads 0 \
-tune zerolatency \
$dir/$name-$(($(ls $dir | grep $name | wc -l)+1)).mkv
