#!/bin/bash
# screen + audio from screen capturing
# { for lectures recording }

pavucontrol & \
killall -9 pavucontrol

dir=$HOME/Videos
name=$(date | awk '{print $2 "-" $3 "-" $7}')

ffmpeg \
-f pulse -ac 2 -ar 96000 -i alsa_output.pci-0000_00_1b.0.iec958-stereo.monitor \
-channel_layout stereo \
-f x11grab \
-framerate 60 \
-draw_mouse 0 \
-s $(xrandr --current | grep -i '*' | awk '{print $1;}') \
-i :0.0+0,0 \
-c:v libx264 \
-preset ultrafast -crf 25 \
-c:a aac \
-threads 0 \
-tune zerolatency \
$dir/$name-$(($(ls $dir | grep $name | wc -l)+1)).mkv
