#!/bin/bash
# 
# (!) uses 'bld' script (!)
# For convenient running of competetive programming tests
# example: './runtests 1.tst'
file="$(pwd)"/$1.tst
bld $1 # build script
num=$(($(grep -o '~' $file | wc -l)-1))
i=0
until [ $i -gt $num ]
do 
    printf "test ( $((i+1)) ) 🠴\n\n"
    in="$(sed -n "/$i:/,/~/p" < $file | sed '1d;$d')"
    printf "Output:"
    printf "\n"
    time echo $in | ./$1
    echo "-------------"
    ((i=i+1))
done
echo "done!"
